// import ShoeMode from './shoe';

// export default ;
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
// import shoeGltf from '@/assets/gltf/shoe.gltf'
import shoeGltf from "./shoe.gltf";

// import sceneGltf from '@/assets/gltf/scene.gltf'

export default function ShoeMode(props) {
  //
  const { scene } = useGLTF(shoeGltf);
  console.log("GLTF", scene);
  return (
    <group {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload(shoeGltf);
